// <auto-generated />
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace NotificationService.UnitTests.BusinessLibrary.Trackers
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using NotificationService.BusinessLibrary.Trackers;
    using NUnit.Framework;

    /// <summary>
    /// Base Test Class.
    /// </summary>
    [ExcludeFromCodeCoverage]
    public class Ctor_Tests : UserConnectionTrackerBaseTests
    {
        /// <summary>
        /// Ctors the null logger.
        /// </summary>
        [Test]
        public void Ctor_NullLogger()
        {
            var ex = Assert.Throws<ArgumentNullException>(() => new UserConnectionTracker(logger: null));
            Assert.IsTrue(ex.ParamName.Equals("logger", StringComparison.OrdinalIgnoreCase));
        }

        /// <summary>
        /// Ctors the valid logger.
        /// </summary>
        [Test]
        public void Ctor_ValidLogger()
        {
            this.SetupBase();
            var userTracker = new UserConnectionTracker(this.loggerMock.Object);
            Assert.IsTrue(userTracker.GetType().FullName.Equals(typeof(UserConnectionTracker).FullName, StringComparison.Ordinal));
        }
    }
}
