// <auto-generated />
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace NotificationService.UnitTests.BusinessLibrary.Trackers
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using System.Linq;
    using NotificationService.Contracts.Models.Trackers;
    using NUnit.Framework;

    /// <summary>
    /// Test class.
    /// </summary>
    /// <seealso cref="NotificationService.UnitTests.BusinessLibrary.Trackers.UserConnectionTrackerBaseTests" />
    [ExcludeFromCodeCoverage]
    public class RemoveConnectionInfo_Tests : UserConnectionTrackerBaseTests
    {
        /// <summary>
        /// Initializes this instance.
        /// </summary>
        [SetUp]
        public void Initialize() => this.SetupBase();

        /// <summary>
        /// Removes the connection information with invalid user object indefier.
        /// </summary>
        /// <param name="userObjectIdentifier">The user object identifier.</param>
        [TestCase(null)]
        [TestCase("")]
        [TestCase(" ")]
        public void RemoveConnectionInfo_WithInvalidUserObjectIndefier(string userObjectIdentifier)
        {
            var ex = Assert.Throws<ArgumentException>(() => this.userConnectionTracker.RemoveConnectionInfo(userObjectIdentifier, "some"));
            Assert.IsTrue(ex.Message.StartsWith("The user object identifier is not specified.", StringComparison.OrdinalIgnoreCase));
        }

        /// <summary>
        /// Removes the connection information with invalid connection identifier.
        /// </summary>
        /// <param name="connectionId">The connection identifier.</param>
        [TestCase(null)]
        [TestCase("")]
        [TestCase(" ")]
        public void RemoveConnectionInfo_WithInvalidConnectionId(string connectionId)
        {
            var ex = Assert.Throws<ArgumentException>(() => this.userConnectionTracker.RemoveConnectionInfo("some", connectionId));
            Assert.IsTrue(ex.Message.StartsWith("The connection Id is not specified.", StringComparison.OrdinalIgnoreCase));
        }

        /// <summary>
        /// Removes the connection information with valid inputs.
        /// </summary>
        [Test]
        public void RemoveConnectionInfo_WithValidInputs()
        {
            string connectionId = Guid.NewGuid().ToString();
            string userOid = "Test Oid";
            UserConnectionInfo userConnectionInfo = new UserConnectionInfo(connectionId);
            this.userConnectionTracker.SetConnectionInfo(userOid, userConnectionInfo);
            this.userConnectionTracker.SetConnectionInfo(userOid, new UserConnectionInfo("some"));

            // Act
            this.userConnectionTracker.RemoveConnectionInfo(userOid, connectionId);
            var set = this.userConnectionTracker.RetrieveConnectionInfo(userOid);
            Assert.IsFalse(set.First().Equals(userConnectionInfo));
            Assert.IsTrue(set.Count == 1);
        }
    }
}
