// <auto-generated />
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace NotificationService.UnitTests.BusinessLibrary.Trackers
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using System.Linq;
    using NotificationService.Contracts.Models.Trackers;
    using NUnit.Framework;

    /// <summary>
    /// Test Class.
    /// </summary>
    /// <seealso cref="UserConnectionTrackerBaseTests" />
    [ExcludeFromCodeCoverage]
    public class RetrieveConnectionInfo_Tests : UserConnectionTrackerBaseTests
    {
        /// <summary>
        /// Initializes this instance.
        /// </summary>
        [SetUp]
        public void Initialize() => this.SetupBase();

        /// <summary>
        /// Rectrieves the connection with invalid user object indefier.
        /// </summary>
        /// <param name="userObjectIdentifier">The user object identifier.</param>
        [TestCase(null)]
        [TestCase("")]
        [TestCase(" ")]
        public void RectrieveConnection_WithInvalidUserObjectIndefier(string userObjectIdentifier)
        {
            var ex = Assert.Throws<ArgumentException>(() => this.userConnectionTracker.RetrieveConnectionInfo(userObjectIdentifier));
            Assert.IsTrue(ex.Message.StartsWith("The user object identifier is not specified.", StringComparison.OrdinalIgnoreCase));
        }

        /// <summary>
        /// Rectrieves the connection with valid user object indefier.
        /// </summary>
        [Test]
        public void RectrieveConnection_WithValidUserObjectIndefier()
        {
            string connectionId = Guid.NewGuid().ToString();
            string userOid = "Test Oid";
            UserConnectionInfo userConnectionInfo = new UserConnectionInfo(connectionId);
            this.userConnectionTracker.SetConnectionInfo(userOid, userConnectionInfo);
            this.userConnectionTracker.SetConnectionInfo(Guid.NewGuid().ToString(), new UserConnectionInfo("some"));
            
            // Act
            var set = this.userConnectionTracker.RetrieveConnectionInfo(userOid);
            Assert.IsTrue(set.First().Equals(userConnectionInfo));
        }
    }
}
