// <auto-generated />
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace NotificationService.UnitTests.BusinessLibrary.Trackers
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using System.Linq;
    using NotificationService.Contracts.Models.Trackers;
    using NUnit.Framework;

    /// <summary>
    /// Test class.
    /// </summary>
    /// <seealso cref="NotificationService.UnitTests.BusinessLibrary.Trackers.UserConnectionTrackerBaseTests" />
    [ExcludeFromCodeCoverage]
    public class SetConnectionInfo_Tests : UserConnectionTrackerBaseTests
    {
        /// <summary>
        /// Initializes this instance.
        /// </summary>
        [SetUp]
        public void Initialize() => this.SetupBase();

        /// <summary>
        /// Sets the connection information with invalid user object indefier.
        /// </summary>
        /// <param name="userObjectIdentifier">The user object identifier.</param>
        [TestCase(null)]
        [TestCase("")]
        [TestCase(" ")]
        public void SetConnectionInfo_WithInvalidUserObjectIndefier(string userObjectIdentifier)
        {
            var ex = Assert.Throws<ArgumentException>(() => this.userConnectionTracker.SetConnectionInfo(userObjectIdentifier, new UserConnectionInfo(Guid.NewGuid().ToString())));
            Assert.IsTrue(ex.Message.StartsWith("The user object identifier is not specified.", StringComparison.OrdinalIgnoreCase));
        }

        /// <summary>
        /// Sets the connection information with null connection information.
        /// </summary>
        [Test]
        public void SetConnectionInfo_WithNullConnectionInfo()
        {
            var ex = Assert.Throws<ArgumentNullException>(() => this.userConnectionTracker.SetConnectionInfo("some", null));
            Assert.IsTrue(ex.ParamName.Equals("userConnectionInfo", StringComparison.Ordinal));
        }

        /// <summary>
        /// Sets the connection information with valid inputs.
        /// </summary>
        [Test]
        public void SetConnectionInfo_WithValidInputs()
        {
            string connectionId = Guid.NewGuid().ToString();
            string userOid = "Test Oid";
            UserConnectionInfo userConnectionInfo = new UserConnectionInfo(connectionId);

            // Act
            this.userConnectionTracker.SetConnectionInfo(userOid, userConnectionInfo);
            this.userConnectionTracker.SetConnectionInfo(Guid.NewGuid().ToString(), new UserConnectionInfo("some"));
            var set = this.userConnectionTracker.RetrieveConnectionInfo(userOid);
            Assert.IsTrue(set.First().Equals(userConnectionInfo));
        }
    }
}
