// <auto-generated />
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace NotificationService.UnitTests.BusinessLibrary.Trackers
{
    using System.Diagnostics.CodeAnalysis;
    using Microsoft.Extensions.Logging;
    using Moq;
    using NotificationService.BusinessLibrary.Trackers;

    /// <summary>
    /// Base Test Class.
    /// </summary>
    [ExcludeFromCodeCoverage]
    public class UserConnectionTrackerBaseTests
    {
        /// <summary>
        /// The logger mock.
        /// </summary>
        protected Mock<ILogger<UserConnectionTracker>> loggerMock;

        /// <summary>
        /// The user connection tracker.
        /// </summary>
        protected UserConnectionTracker userConnectionTracker;

        /// <summary>
        /// Setups the base.
        /// </summary>
        public void SetupBase()
        {
            this.loggerMock = new Mock<ILogger<UserConnectionTracker>>();
            this.userConnectionTracker = new UserConnectionTracker(this.loggerMock.Object);
        }
    }
}
