// <autogenerated />
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace NotificationService.UnitTests.Common.Exceptions.NotificationServiceException_Tests
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using NotificationService.Common.Exceptions;
    using NUnit.Framework;

    [ExcludeFromCodeCoverage]
    public class NotificationServiceException_Ctor_Tests
    {
        [Test]
        public void Ctor_NoParameters()
        {
            var ex = new NotificationServiceException();
            Assert.AreEqual(ex.Message, "Something went wrong!");
        }

        [Test]
        public void Ctor_ValidMessage()
        {
            var ex = new NotificationServiceException("Test Message");
            Assert.AreEqual(ex.Message, "Test Message");
        }

        [Test]
        public void Ctor_ValidMessageInnerException()
        {
            var ex = new NotificationServiceException("Test Message", new Exception("Test Exception"));
            Assert.AreEqual(ex.Message, "Test Message");
            Assert.AreEqual(ex.InnerException.Message, "Test Exception");
        }
    }
}
