// <auto-generated />
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace NotificationService.UnitTests.BusinessLibrary.Trackers.UserConnectionCacheTracker_Tests
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics.CodeAnalysis;
    using System.Linq;
    using System.Text;
    using System.Text.Json;
    using System.Threading;
    using System.Threading.Tasks;
    using Moq;
    using NotificationService.Contracts.Models.Trackers;
    using NUnit.Framework;

    /// <summary>
    /// Test Class.
    /// </summary>
    /// <seealso cref="UserConnectionCacheTrackerBaseTests" />
    [ExcludeFromCodeCoverage]
    public class RetrieveConnectionInfo_Tests : UserConnectionCacheTrackerBaseTests
    {
        /// <summary>
        /// Initializes this instance.
        /// </summary>
        [SetUp]
        public void Initialize() => this.SetupBase();

        /// <summary>
        /// Rectrieves the connection with invalid user object indefier.
        /// </summary>
        /// <param name="userObjectIdentifier">The user object identifier.</param>
        [TestCase(null)]
        [TestCase("")]
        [TestCase(" ")]
        public void RectrieveConnection_WithInvalidUserObjectIndefier(string userObjectIdentifier)
        {
            var ex = Assert.Throws<ArgumentException>(() => this.userConnectionCacheTracker.RetrieveConnectionInfo(userObjectIdentifier));
            Assert.IsTrue(ex.Message.StartsWith("The user object identifier is not specified.", StringComparison.OrdinalIgnoreCase));
        }

        /// <summary>
        /// Rectrieves the connection with valid user object indefier.
        /// </summary>
        [Test]
        public void RectrieveConnection_WithValidUserObjectIndefier()
        {
            string connectionId = Guid.NewGuid().ToString();
            string userOid = "Test Oid";
            UserConnectionInfo userConnectionInfo = new UserConnectionInfo(connectionId, "Some App");
            HashSet<UserConnectionInfo> connectionSet = new HashSet<UserConnectionInfo>();
            connectionSet.Add(userConnectionInfo);
            this.distributedCacheMock.Setup(dc => dc.GetAsync(It.IsAny<string>(), It.IsAny<CancellationToken>())).Returns(Task.FromResult<byte[]>(Encoding.UTF8.GetBytes(JsonSerializer.Serialize(connectionSet))));

            // Act
            var set = this.userConnectionCacheTracker.RetrieveConnectionInfo(userOid);
            this.distributedCacheMock.Verify(dc => dc.GetAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()), Times.Once);
            Assert.AreEqual(set.First().ConnectionId, connectionId);
        }
    }
}
