// <auto-generated />
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace NotificationService.UnitTests.BusinessLibrary.Trackers.UserConnectionCacheTracker_Tests
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Extensions.Caching.Distributed;
    using Moq;
    using NotificationService.Contracts.Models.Trackers;
    using NUnit.Framework;

    /// <summary>
    /// Test class.
    /// </summary>
    /// <seealso cref="UserConnectionCacheTrackerBaseTests" />
    [ExcludeFromCodeCoverage]
    public class SetConnectionInfo_Tests : UserConnectionCacheTrackerBaseTests
    {
        /// <summary>
        /// Initializes this instance.
        /// </summary>
        [SetUp]
        public void Initialize() => this.SetupBase();

        /// <summary>
        /// Sets the connection information with invalid user object indefier.
        /// </summary>
        /// <param name="userObjectIdentifier">The user object identifier.</param>
        [TestCase(null)]
        [TestCase("")]
        [TestCase(" ")]
        public void SetConnectionInfo_WithInvalidUserObjectIndefier(string userObjectIdentifier)
        {
            var ex = Assert.Throws<ArgumentException>(() => this.userConnectionCacheTracker.SetConnectionInfo(userObjectIdentifier, new UserConnectionInfo(Guid.NewGuid().ToString())));
            Assert.IsTrue(ex.Message.StartsWith("The user object identifier is not specified.", StringComparison.OrdinalIgnoreCase));
        }

        /// <summary>
        /// Sets the connection information with null connection information.
        /// </summary>
        [Test]
        public void SetConnectionInfo_WithNullConnectionInfo()
        {
            var ex = Assert.Throws<ArgumentNullException>(() => this.userConnectionCacheTracker.SetConnectionInfo("some", null));
            Assert.IsTrue(ex.ParamName.Equals("userConnectionInfo", StringComparison.Ordinal));
        }

        /// <summary>
        /// Sets the connection information with valid inputs.
        /// </summary>
        [Test]
        public void SetConnectionInfo_WithValidInputs()
        {
            string connectionId = Guid.NewGuid().ToString();
            string userOid = "Test Oid";
            UserConnectionInfo userConnectionInfo = new UserConnectionInfo(connectionId);
            this.distributedCacheMock.Setup(dc => dc.GetAsync(It.IsAny<string>(), It.IsAny<CancellationToken>())).Returns(Task.FromResult<byte[]>(null));
            this.distributedCacheMock.Setup(dc => dc.SetAsync(It.IsAny<string>(), It.IsAny<byte[]>(), It.IsAny<DistributedCacheEntryOptions>(), It.IsAny<CancellationToken>())).Returns(Task.CompletedTask);
            // Act
            this.userConnectionCacheTracker.SetConnectionInfo(userOid, userConnectionInfo);
            this.distributedCacheMock.Verify(dc => dc.GetAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()), Times.Once);
            this.distributedCacheMock.Verify(dc => dc.SetAsync(It.IsAny<string>(), It.IsAny<byte[]>(), It.IsAny<DistributedCacheEntryOptions>(), It.IsAny<CancellationToken>()), Times.Once);
        }
    }
}
