// <auto-generated />
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace NotificationService.UnitTests.BusinessLibrary.Trackers.UserConnectionCacheTracker_Tests
{
    using System.Diagnostics.CodeAnalysis;
    using Microsoft.Extensions.Caching.Distributed;
    using Microsoft.Extensions.Logging;
    using Moq;
    using NotificationService.BusinessLibrary.Trackers;

    /// <summary>
    /// Base Test Class.
    /// </summary>
    [ExcludeFromCodeCoverage]
    public class UserConnectionCacheTrackerBaseTests
    {
        /// <summary>
        /// The logger mock.
        /// </summary>
        protected Mock<ILogger<UserConnectionTracker>> loggerMock;

        /// <summary>
        /// The distributed cache mock.
        /// </summary>
        protected Mock<IDistributedCache> distributedCacheMock;

        /// <summary>
        /// The user connection tracker.
        /// </summary>
        protected UserConnectionCacheTracker userConnectionCacheTracker;

        /// <summary>
        /// Setups the base.
        /// </summary>
        public void SetupBase()
        {
            this.loggerMock = new Mock<ILogger<UserConnectionTracker>>();
            this.distributedCacheMock = new Mock<IDistributedCache>();
            this.userConnectionCacheTracker = new UserConnectionCacheTracker(this.distributedCacheMock.Object, this.loggerMock.Object);
        }
    }
}
