// <autogenerated />
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace NotificationService.UnitTests.Controllers.V1.NotificationsController_Tests
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using WebNotifications.Controllers.V1;
    using NUnit.Framework;

    /// <summary>
    /// Test Base class
    /// </summary>
    [ExcludeFromCodeCoverage]
    public class Ctor_Tests : NotificationsControllerBaseTest
    {
        [Test]
        public void Ctor_NullNotificationsManager()
        {
            this.SetupBase();
            var ex = Assert.Throws<ArgumentNullException>(() => new NotificationsController(null, this.LoggerMock.Object));
            Assert.IsTrue(ex.ParamName.Equals("notificationsManager", StringComparison.OrdinalIgnoreCase));
        }

        [Test]
        public void Ctor_NullLogger()
        {
            this.SetupBase();
            var ex = Assert.Throws<ArgumentNullException>(() => new NotificationsController(this.NotificationsManagerMock.Object, null));
            Assert.IsTrue(ex.ParamName.Equals("logger", StringComparison.OrdinalIgnoreCase));
        }

        /// <summary>
        /// Ctors the valid input.
        /// </summary>
        [Test]
        public void Ctor_ValidInput()
        {
            this.SetupBase();
            var controller = new NotificationsController(this.NotificationsManagerMock.Object, this.LoggerMock.Object);
            Assert.IsTrue(controller.GetType().FullName.Equals(typeof(NotificationsController).FullName, StringComparison.Ordinal));
        }
    }
}
