// <autogenerated />
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace NotificationService.UnitTests.Controllers.V1.NotificationsController_Tests
{
    using System.Collections.Generic;
    using System.Diagnostics.CodeAnalysis;
    using System.Security.Claims;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;
    using Moq;
    using NotificationService.BusinessLibrary.Interfaces;
    using NotificationService.SvCommon.APIConstants;
    using WebNotifications.Channels;
    using WebNotifications.Controllers.V1;

    /// <summary>
    /// Test Base class
    /// </summary>
    [ExcludeFromCodeCoverage]
    public class NotificationsControllerBaseTest
    {
        /// <summary>
        /// Gets the notifications manager mock.
        /// </summary>
        /// <value>
        /// The notifications manager mock.
        /// </value>
        protected Mock<INotificationsManager> NotificationsManagerMock { get; private set; }

        /// <summary>
        /// Gets the channel mock.
        /// </summary>
        /// <value>
        /// The channel mock.
        /// </value>
        protected Mock<INotificationsChannel> NotificationsChannelMock { get; private set; }

        /// <summary>
        /// Gets the logger mock.
        /// </summary>
        /// <value>
        /// The logger mock.
        /// </value>
        protected Mock<ILogger<NotificationsController>> LoggerMock { get; private set; }

        /// <summary>
        /// Gets the notifications controller object.
        /// </summary>
        /// <value>
        /// The notifications controller object.
        /// </value>
        protected NotificationsController NotificationsControllerObject { get; private set; }

        /// <summary>
        /// Gets the name of the application.
        /// </summary>
        /// <value>
        /// The name of the application.
        /// </value>
        protected string ApplicationName { get; } = "Application 1";

        /// <summary>
        /// Setups the base.
        /// </summary>
        protected void SetupBase()
        {
            this.NotificationsManagerMock = new Mock<INotificationsManager>();
            this.NotificationsChannelMock = new Mock<INotificationsChannel>();
            this.LoggerMock = new Mock<ILogger<NotificationsController>>();
            this.NotificationsControllerObject = new NotificationsController(this.NotificationsManagerMock.Object, this.LoggerMock.Object)
            {
                ControllerContext = new ControllerContext
                {
                    HttpContext = new DefaultHttpContext(),
                },
            };
            Claim claim = new Claim(ClaimTypeConstants.ObjectIdentifier, "test object identifier.");
            ClaimsIdentity claimsIdentity = new ClaimsIdentity(new List<Claim> { claim });
            this.NotificationsControllerObject.ControllerContext.HttpContext.User = new ClaimsPrincipal(claimsIdentity);
        }
    }
}
